import projectsData from '../../data/projects.json';
import employmentData from '../../data/employment.json';
import type { Locale, PortfolioData, Project, Experience } from '../constants/content';

const PROJECTS_BY_LOCALE: Record<Locale, Project[]> = {
  en: projectsData as Project[],
  hi: [
    { title: 'सिग्नेचर प्राइवेट क्लाउड', role: 'क्लाउड यूआई / फुल स्टैक', description: 'एंटरप्राइज़ प्राइवेट क्लाउड प्लेटफ़ॉर्म के लिए क्लाउड यूआई विकसित किया। KMS, EIP, CLS, CAU, VPS, CBS और IAM पर काम किया, ताकि सुरक्षित एक्सेस कंट्रोल सुनिश्चित हो। रियल-टाइम Grafana मॉनिटरिंग डैशबोर्ड बनाए।', tech: ['Next.js', 'React.js', 'TypeScript', 'Material UI'], metrics: 'सुगम और स्केलेबल इंटरफ़ेस के साथ कुशल क्लाउड रिसोर्स मैनेजमेंट।' },
    { title: 'माइलसुम', role: 'फुल स्टैक / बैकएंड', description: 'CRM, ऑपरेशंस, अकाउंटिंग और टास्क मैनेजमेंट मॉड्यूल के साथ मल्टी-टेनेन्ट बिज़नेस प्लेटफ़ॉर्म डिजाइन किया। फ्रंटएंड Redux से स्टेट संभालता है, जबकि बैकएंड Laravel और Node.js से रियल-टाइम एनालिटिक्स के साथ बिज़नेस लॉजिक चलाता है।', tech: ['React.js', 'TypeScript', 'Laravel', 'Node.js', 'Express', 'MySQL'], metrics: 'डायनेमिक, स्केलेबल रियल-टाइम डेटा प्रोसेसिंग और एंटरप्राइज़ इन्फ़ॉर्मेशन।' },
    { title: 'फंडिवर', role: 'फ्रंटएंड / यूआई इंजीनियर', description: 'लेंडर्स, ब्रोकर्स और बोररॉवर के लिए लैंड और कमर्शियल लेंडिंग प्रक्रिया को सरल बनाने वाला मार्केटप्लेस। Formik और Yup वैलिडेशन के साथ जटिल एप्लिकेशन फॉर्म मैनेज किए।', tech: ['React.js', 'Redux', 'TypeScript', 'Bootstrap 5'], metrics: 'परंपरागत रूप से लंबी लेंडिंग प्रक्रिया को डिजिटल और सरल बनाया।' },
    { title: 'कार्लटन वन', role: 'बैकएंड / माइक्रोसर्विसेज', description: 'नामांकन और अवार्ड मैनेजमेंट के लिए पोर्टल। Nomination, Award और ऐप डाउनलोड लिंक के लिए मुख्य माइक्रोसर्विसेज विकसित कीं, साथ ही फ्रंटएंड मॉड्यूल को इंटीग्रेट किया।', tech: ['Node.js', 'Express', 'Vue.js'], metrics: 'कई एंटरप्राइज़ क्लाइंट्स के लिए अत्यंत अलग-थलग आर्किटेक्चर।' },
    { title: 'Trea360', role: 'फुल स्टैक इंजीनियर', description: 'लैंडस्केपिंग और कंस्ट्रक्शन कंपनियों के लिए ERP समाधान विकसित किया, जिसमें Workflow, dispatch management और HRM के लिए बड़े मॉड्यूल थे।', tech: ['Angular', 'Laravel', 'Bootstrap'], metrics: 'कंस्ट्रक्शन के लिए व्यापक बिज़नेस प्रोसेस ऑटोमेशन।' },
    { title: 'टिकटगेटवे', role: 'PHP / वेब डेवलपर', description: 'ऑनलाइन पोर्टल (ticketgateway.com) जहाँ टिकट और कॉस्ट्यूम ऑनलाइन खरीदे व बेचे जाते हैं। उपयोगकर्ताओं के लिए इवेंट बनाना और टिकेट इन्वेंटरी मैनेज करना आसान बनाने के लिए कस्टम लॉजिक विकसित किया।', tech: ['Codeigniter', 'HTML', 'CSS', 'jQuery'], metrics: 'मजबूत इवेंट क्रिएशन और मार्केटप्लेस इंजन।' },
    { title: 'मोनाब', role: 'PHP / वेब डेवलपर', description: 'ऑनलाइन पोर्टल (ticketgateway.com) जहाँ टिकट और कॉस्ट्यूम ऑनलाइन खरीदे व बेचे जाते हैं। उपयोगकर्ताओं के लिए इवेंट बनाना और टिकेट इन्वेंटरी मैनेज करना आसान बनाने के लिए कस्टम लॉजिक विकसित किया।', tech: ['Codeigniter', 'HTML', 'CSS', 'jQuery'], metrics: 'मजबूत इवेंट क्रिएशन और मार्केटप्लेस इंजन।' }
  ],
  ar: [
    { title: 'Signature Private Cloud', role: 'واجهة سحابية / Full Stack', description: 'طورت واجهة السحابة لمنصة سحابية خاصة للمؤسسات تدير الخدمات الأساسية. عملت على KMS وEIP وCLS وCAU وVPS وCBS وIAM للتحكم الآمن في الوصول. بنيت لوحات مراقبة Grafana في الوقت الفعلي.', tech: ['Next.js', 'React.js', 'TypeScript', 'Material UI'], metrics: 'واجهات بديهية وقابلة للتوسع لإدارة موارد السحابة بكفاءة.' },
    { title: 'Milesum', role: 'Full Stack / Backend', description: 'صممت منصة أعمال متعددة المستأجرين بموديولات CRM والعمليات والمحاسبة وإدارة المهام. تتعامل الواجهة الأمامية مع الحالة عبر Redux، بينما يستخدم الخلفية Laravel وNode.js من أجل منطق العمل والتحليلات في الوقت الفعلي.', tech: ['React.js', 'TypeScript', 'Laravel', 'Node.js', 'Express', 'MySQL'], metrics: 'معالجة بيانات في الوقت الفعلي وقابلة للتطوير وتوليد رؤى مؤسسية.' },
    { title: 'Fundever', role: 'مهندس واجهة / واجهة مستخدم', description: 'سوق يبسّط عملية الإقراض العقاري والتجاري للبنوك والمستشارين والمقترضين. أدار نماذج التطبيق المعقدة باستخدام Formik وYup للتحقق من الصحة.', tech: ['React.js', 'Redux', 'TypeScript', 'Bootstrap 5'], metrics: 'رقمن وتبسيط عملية إقراض كانت مرهقة تقليديًا.' },
    { title: 'Carlton One', role: 'Backend / Microservices', description: 'بوابة لإدارة الترشيحات والجوائز. هندست الخدمات الصغيرة الأساسية لـ Nomination وAward وروابط تنزيل التطبيق، مع دمج وحدات الواجهة الأمامية.', tech: ['Node.js', 'Express', 'Vue.js'], metrics: 'بنية عالية الفصل تخدم عدة عملاء مؤسسيين.' },
    { title: 'Trea360', role: 'مهندس Full Stack', description: 'طورت حل ERP لشركات تنسيق الحدائق والبناء يضم وحدات ضخمة لإدارة سير العمل، إدارة الإيصال، وإدارة الموارد البشرية.', tech: ['Angular', 'Laravel', 'Bootstrap'], metrics: 'أتمتة شاملة لعمليات الأعمال في البناء.' },
    { title: 'Ticketgateway', role: 'PHP / مطور ويب', description: 'بوابة إلكترونية (ticketgateway.com) لشراء وبيع التذاكر والمُلبسات عبر الإنترنت. صممت منطقًا مخصصًا يسمح للمستخدمين بإنشاء الفعاليات وإدارة مخزون التذاكر بسلاسة.', tech: ['Codeigniter', 'HTML', 'CSS', 'jQuery'], metrics: 'محرك قوي لإنشاء الفعاليات والسوق الإلكتروني.' },
    { title: 'MonaB', role: 'PHP / مطور ويب', description: 'بوابة إلكترونية (ticketgateway.com) لشراء وبيع التذاكر والمُلبسات عبر الإنترنت. صممت منطقًا مخصصًا يسمح للمستخدمين بإنشاء الفعاليات وإدارة مخزون التذاكر بسلاسة.', tech: ['Codeigniter', 'HTML', 'CSS', 'jQuery'], metrics: 'محرك قوي لإنشاء الفعاليات والسوق الإلكتروني.' }
  ],
  fr: [
    { title: 'Signature Private Cloud', role: 'UI cloud / Full Stack', description: 'Développement de l’interface cloud d’une plateforme privée d’entreprise gérant des services essentiels. Travaux sur KMS, EIP, CLS, CAU, VPS, CBS et IAM pour sécuriser les accès. Création de tableaux de bord Grafana en temps réel.', tech: ['Next.js', 'React.js', 'TypeScript', 'Material UI'], metrics: 'Interfaces intuitives et évolutives pour une gestion efficace des ressources cloud.' },
    { title: 'Milesum', role: 'Full Stack / Backend', description: 'Conception d’une plateforme d’entreprise multi-locataire avec modules CRM, opérations, comptabilité et gestion des tâches. Le frontend gère l’état via Redux ; le backend exploite Laravel pour la logique métier et Node.js pour l’analyse en temps réel.', tech: ['React.js', 'TypeScript', 'Laravel', 'Node.js', 'Express', 'MySQL'], metrics: 'Traitement dynamique de données en temps réel et analyse d’entreprise évolutive.' },
    { title: 'Fundever', role: 'Frontend / UI Engineer', description: 'Marketplace simplifiant le processus de prêt immobilier et commercial pour les prêteurs, courtiers et emprunteurs. Gestion de formulaires complexes avec Formik et validation Yup.', tech: ['React.js', 'Redux', 'TypeScript', 'Bootstrap 5'], metrics: 'Numérisation et simplification d’un processus de prêt traditionnellement fastidieux.' },
    { title: 'Carlton One', role: 'Backend / Microservices', description: 'Portail de gestion des nominations et récompenses. Conception de microservices clés pour Nomination, Award et liens de téléchargement d’applications, avec intégration des modules frontend.', tech: ['Node.js', 'Express', 'Vue.js'], metrics: 'Architecture hautement découplée servant plusieurs clients entreprise.' },
    { title: 'Trea360', role: 'Ingénieur Full Stack', description: 'Développement d’une solution ERP pour les sociétés de paysage et de construction avec modules lourds de gestion de workflow, de dispatch et de RH.', tech: ['Angular', 'Laravel', 'Bootstrap'], metrics: 'Automatisation complète des processus métier pour la construction.' },
    { title: 'Ticketgateway', role: 'PHP / Développeur Web', description: 'Portail en ligne (ticketgateway.com) pour acheter et vendre des billets et costumes en ligne. Conception d’une logique sur mesure qui permet aux utilisateurs de créer des événements et de gérer l’inventaire.', tech: ['Codeigniter', 'HTML', 'CSS', 'jQuery'], metrics: 'Moteur robuste de création d’événements et de marketplace.' },
    { title: 'MonaB', role: 'PHP / Développeur Web', description: 'Portail en ligne (ticketgateway.com) pour acheter et vendre des billets et costumes en ligne. Conception d’une logique sur mesure qui permet aux utilisateurs de créer des événements et de gérer l’inventaire.', tech: ['Codeigniter', 'HTML', 'CSS', 'jQuery'], metrics: 'Moteur robuste de création d’événements et de marketplace.' }
  ]
};

const EMPLOYMENT_BY_LOCALE: Record<Locale, Experience[]> = {
  en: employmentData as Experience[],
  hi: [
    { period: 'जनवरी 2025 – वर्तमान', role: 'लीड सॉफ़्टवेयर इंजीनियर', company: 'Impetus Technologies India Pvt. Ltd. (पुणे, भारत)', details: ['12-इंजीनियर टीम का नेतृत्व sprints, stand-ups, retrospectives और रोज़ाना डिलीवरी समन्वय के साथ किया।', 'एंड-टू-एंड user stories की डिलीवरी की जिम्मेदारी, TDD और BDD के साथ रखरखाव योग्य समाधान तैयार किए।', 'SonarQube, structured GitHub pull request reviews और साझा गुणवत्ता अभ्यास के माध्यम से इंजीनियरिंग मानक उठाए।', 'डिज़ाइन दस्तावेज़ और hands-on frontend सुधारों के माध्यम से तकनीकी दिशा दी।'] },
    { period: 'अप्रैल 2022 – जुलाई 2024', role: 'डेवलपमेंट इंजीनियर', company: 'Big Water Consulting SCS (ब्रसेल्स, बेल्जियम)', details: ['6-व्यक्ति टीम का प्रबंधन करते हुए user stories को आकार दिया और Express-based microservices बनाये।', 'TEST और PROD के लिए Jenkins और GitHub deployment workflow बनाया जो टीम के लिए पुनरावृत्ति योग्य release path प्रदान करता है।', 'पूर्ण invoice module की डिलीवरी की, जिसमें automated generation और dashboard reporting widgets शामिल थे।', 'Docker, Translate API integration और SonarQube quality checks के साथ व्यावहारिक इंजीनियरिंग नींव स्थापित की।'] },
    { period: 'जनवरी 2019 – अप्रैल 2022', role: 'टेक लीड', company: 'Torinit Consulting Services Pvt. Ltd. (नागपुर, भारत)', details: ['12-व्यक्ति टीम का प्रबंधन किया और Node.js/Express microservices के विकास को योजना से डिलीवरी तक दिशा दी।', 'React.js, Node.js और Twilio का उपयोग करके audio और video communication modules लागू किए।', 'Next.js server-side rendering और custom Magento 2 API connection modules पर आर्किटेक्चर निर्णय लिए।', 'TDD practices, UI design refresh और reusable form-validation libraries के साथ टीम की गुणवत्ता और developer experience में सुधार किया।'] },
    { period: 'जुलाई 2014 – जनवरी 2019', role: 'टेक लीड', company: 'TIU Consulting Pvt. Ltd. (नागपुर, भारत)', details: ['4-व्यक्ति टीम का नेतृत्व discovery, estimation, client demos और deployment तक full delivery lifecycle में किया।', 'Magento 1 और Magento 2 समाधान में जटिल commerce requirements को stakeholder के निकट रखते हुए ट्रांसलेट किया।', 'CakePHP और CodeIgniter का उपयोग करके स्केलेबल web applications विकसित किए।'] },
    { period: 'मई 2011 – जुलाई 2014', role: 'प्रोजेक्ट मैनेजर', company: 'India Active Software Inc. (नागपुर, भारत)', details: ['needs analysis, documentation, coordination, delivery और deployment सहित complete project lifecycle का प्रबंधन किया।', 'PHP, AJAX और MySQL का उपयोग करके ERP विकास के दौरान प्लेटफ़ॉर्म आर्किटेक्चर को आकार दिया।'] },
    { period: 'फरवरी 2010 – अप्रैल 2011', role: 'PHP डेवलपर', company: 'Snehal System (नागपुर, भारत)', details: ['वेबसाइट और वेब एप्लिकेशन के डिजाइन और विकास की जिम्मेदारी संभाली, PHP, JavaScript, Ajax, JSON और visual communication में नींव बनाई।'] },
    { period: 'अक्टूबर 2008 – मई 2009', role: 'सॉफ़्टवेयर इंजीनियर', company: 'Prolifics Software & Technologies (पुणे, भारत)', details: ['PHP, JavaScript और Photoshop का उपयोग करके core websites और web applications बनाकर अपनी इंजीनियरिंग यात्रा शुरू की।'] }
  ],
  ar: [
    { period: 'يناير 2025 – حتى الآن', role: 'مهندس برمجيات أول', company: 'Impetus Technologies India Pvt. Ltd. (بونه، الهند)', details: ['قادت فريقًا مكونًا من 12 مهندسًا عبر تخطيط السباقات، الاجتماعات اليومية، المراجعات، وتنسيق التسليم اليومي.', 'أُشرفت على تسليم قصص المستخدم من البداية إلى النهاية، بمساعدة الفريق على تحويل المتطلبات إلى حلول قابلة للصيانة باستخدام TDD وBDD.', 'رفعت مستويات الهندسة عبر SonarQube ومراجعات pull request في GitHub وممارسات الجودة المشتركة.', 'قدّمت توجيهًا تقنيًا من خلال مستندات التصميم وتحسينات واجهة أمامية مباشرة تحافظ على توافق المنتج والهندسة.'] },
    { period: 'أبريل 2022 – يوليو 2024', role: 'مهندس تطوير', company: 'Big Water Consulting SCS (بروكسل، بلجيكا)', details: ['أدير فريقًا مكونًا من 6 أشخاص بينما أصوغ قصص المستخدم وأسلم خدمات microservices قائمة على Express.', 'أنشأت سير عمل النشر عبر Jenkins وGitHub لـ TEST وPROD، مما أعطى الفريق مسار إصدارات قابل للتكرار.', 'قادت تنفيذ وحدة فاتورة كاملة مع إنشاء تلقائي ولوحات تقارير.', 'أسست أسس هندسية عملية عبر Docker، تكامل Translate API، وفحوصات جودة SonarQube.'] },
    { period: 'يناير 2019 – أبريل 2022', role: 'قائد فني', company: 'Torinit Consulting Services Pvt. Ltd. (ناغبور، الهند)', details: ['أدير فريقًا من 12 شخصًا وأرشد تطوير microservices باستخدام Node.js وExpress من التخطيط إلى التسليم.', 'قادت تنفيذ وحدات الاتصال الصوتية والفيديو باستخدام React.js وNode.js وTwilio.', 'اتخذت قرارات هندسية حول Next.js SSR والوصلات المخصصة لـ Magento 2 API.', 'حسّنت جودة الفريق وتجربة المطورين عبر TDD، تجديد واجهة المستخدم، وإنشاء مكتبات reusable form validation.'] },
    { period: 'يوليو 2014 – يناير 2019', role: 'قائد فني', company: 'TIU Consulting Pvt. Ltd. (ناغبور، الهند)', details: ['قادت فريقًا مكونًا من 4 أشخاص عبر دورة حياة التسليم الكاملة من الاكتشاف والتقدير إلى العروض التقديمية والتوزيع.', 'ترجمت متطلبات التجارة المعقدة إلى حلول Magento 1 وMagento 2 مع إبقاء أصحاب المصلحة قريبين من التسليم.', 'وجهت تطوير تطبيقات ويب قابلة للتوسع باستخدام CakePHP وCodeIgniter.'] },
    { period: 'مايو 2011 – يوليو 2014', role: 'مدير مشروع', company: 'India Active Software Inc. (ناغبور، الهند)', details: ['أدير دورة حياة المشروع كاملة بما فيها تحليل الاحتياجات والتوثيق والتنسيق والتسليم والنشر.', 'ساعدت في تشكيل هيكلية النظام أثناء قيادة تطوير ERP باستخدام PHP وAJAX وMySQL.'] },
    { period: 'فبراير 2010 – أبريل 2011', role: 'مطور PHP', company: 'Snehal System (ناغبور، الهند)', details: ['تحمل تصميم وتطوير مواقع وتطبيقات الويب، وبنيت قاعدة قوية في PHP وJavaScript وAjax وJSON والتواصل البصري.'] },
    { period: 'أكتوبر 2008 – مايو 2009', role: 'مهندس برمجيات', company: 'Prolifics Software & Technologies (بونه، الهند)', details: ['بدأت مسيرتي الهندسية بتصميم وتطوير المواقع الأساسية وتطبيقات الويب باستخدام PHP وJavaScript وPhotoshop.'] }
  ],
  fr: [
    { period: 'Janvier 2025 – Aujourd’hui', role: 'Lead Software Engineer', company: 'Impetus Technologies India Pvt. Ltd. (Pune, Inde)', details: ['Dirige une équipe de 12 ingénieurs sur la planification sprint, stand-ups, retrospectives et coordination quotidienne de la livraison.', 'Maîtrise la livraison des user stories de bout en bout, aidant l’équipe à transformer les exigences en solutions maintenables avec TDD et BDD.', 'Améliore les standards techniques via SonarQube, revues GitHub structurées et pratiques de qualité partagées.', 'Apporte une direction technique via documents de conception et améliorations frontend concrètes alignant produit et engineering.'] },
    { period: 'Avril 2022 – Juillet 2024', role: 'Development Engineer', company: 'Big Water Consulting SCS (Bruxelles, Belgique)', details: ['Gère une équipe de 6 personnes en formant les user stories et en livrant des microservices Express.', 'Crée le workflow de déploiement Jenkins et GitHub pour TEST et PROD, donnant à l’équipe un chemin de release reproductible.', 'Dirige la livraison d’un module de facture complet avec génération automatique et widgets de reporting.', 'Établit des fondations techniques pratiques grâce à Docker, intégration Translate API et contrôles qualité SonarQube.'] },
    { period: 'Janvier 2019 – Avril 2022', role: 'Tech Lead', company: 'Torinit Consulting Services Pvt. Ltd. (Nagpur, Inde)', details: ['Gère une équipe de 12 personnes et pilote le développement de microservices Node.js et Express de la planification à la livraison.', 'Dirige la mise en œuvre de modules de communication audio/vidéo via React.js, Node.js et Twilio.', 'Prend des décisions d’architecture autour de Next.js SSR et de modules de connexion Magento 2 API personnalisés.', 'Améliore la qualité et l’expérience développeur grâce à TDD, refonte UI et bibliothèques de validation de formulaire réutilisables.'] },
    { period: 'Juillet 2014 – Janvier 2019', role: 'Tech Lead', company: 'TIU Consulting Pvt. Ltd. (Nagpur, Inde)', details: ['Dirige une équipe de 4 personnes sur tout le cycle de vie, de la découverte à la démonstration client et au déploiement.', 'Traduit des exigences e-commerce complexes en solutions Magento 1 et Magento 2 tout en gardant les parties prenantes proches du delivery.', 'Guide le développement d’applications web évolutives avec CakePHP et CodeIgniter.'] },
    { period: 'Mai 2011 – Juillet 2014', role: 'Project Manager', company: 'India Active Software Inc. (Nagpur, Inde)', details: ['Gère le cycle de vie complet du projet, incluant analyse des besoins, documentation, coordination, livraison et déploiement.', 'Aide à définir l’architecture plateforme pendant le développement d’un ERP en PHP, AJAX et MySQL.'] },
    { period: 'Février 2010 – Avril 2011', role: 'PHP Developer', company: 'Snehal System (Nagpur, Inde)', details: ['Assure la conception et le développement de sites web et applications, en construisant une base solide en PHP, JavaScript, Ajax, JSON et communication visuelle.'] },
    { period: 'Octobre 2008 – Mai 2009', role: 'Software Engineer', company: 'Prolifics Software & Technologies (Pune, Inde)', details: ['Commence sa carrière en concevant et développant des sites web et applications PHP, JavaScript et Photoshop.'] }
  ]
};

export const getProjectsData = (locale: Locale = 'en', fallback: Project[] = projectsData as Project[]): Project[] => {
  const localProjects = PROJECTS_BY_LOCALE[locale] ?? PROJECTS_BY_LOCALE.en;
  return fallback.map((item, index) => ({ ...item, ...(localProjects[index] ?? {}) }));
};

export const getEmploymentData = (locale: Locale = 'en', fallback: Experience[] = employmentData as Experience[]): Experience[] => {
  const localExperience = EMPLOYMENT_BY_LOCALE[locale] ?? EMPLOYMENT_BY_LOCALE.en;
  return fallback.map((item, index) => ({ ...item, ...(localExperience[index] ?? {}) }));
};

export const loadPortfolioData = (locale: Locale = 'en'): PortfolioData => ({
  projects: getProjectsData(locale),
  experience: getEmploymentData(locale)
});

export type { PortfolioData, Project, Experience };
